// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $create from "./routes/create.tsx";
import * as $index from "./routes/index.tsx";
import * as $search from "./routes/search.tsx";
import * as $CreatePostForm from "./islands/CreatePostForm.tsx";
import * as $SearchComponent from "./islands/SearchComponent.tsx";
import * as $ViewToggle from "./islands/ViewToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/create.tsx": $create,
    "./routes/index.tsx": $index,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/CreatePostForm.tsx": $CreatePostForm,
    "./islands/SearchComponent.tsx": $SearchComponent,
    "./islands/ViewToggle.tsx": $ViewToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
